language: generic
sudo: true
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_b66253ec584a_key -iv $encrypted_b66253ec584a_iv -in service-worker.json.enc -out service-worker.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project <project-name>
  - gcloud config set compute/zone <zone>
  - gcloud container clusters get-credentials <cluster-name>
  - gcloud container clusters create <cluster-name> --zone <zone>
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t jigglybytez/kubert -f ./server/Dockerfile ./server
script:
  - docker run -e CI=true jigglybytez/kubert npm run test
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
