apiVersion: skaffold/v2beta6
kind: Config
metadata:
  name: kubert
build:
  artifacts:
    - image: jigglybytez/kubert
      context: server
deploy:
  kubectl:
    manifests:
      - k8s/load-balancer-service.yaml
      - k8s/server-deployment.yaml
portForward:
  - resourceType: deployment
    resourceName: server
    port: 5000
    localPort: 5000
